Test branch settings activity into development
aufgabe3lab/MaraudersMap pull request #28
Opened 2023-01-04 18:47 UTC by julianertle

Test class for the settings activity

2023-01-04 20:22 UTC, FelixAlexK requested changes

2023-01-04 20:22 UTC, FelixAlexK commented on app/src/androidTest/java/com/example/maraudersmap/SettingsActivityTest.kt
> +    val testName = TestName()
?

2023-01-04 20:22 UTC, FelixAlexK commented on app/src/androidTest/java/com/example/maraudersmap/SettingsActivityTest.kt
> +class SettingsActivityTest {
Class name should be changed to SettingsActivityInstrumentedTest, because of the reason that it is an Instrumented test not a unit test

2023-01-04 20:22 UTC, FelixAlexK commented on app/src/androidTest/java/com/example/maraudersmap/SettingsActivityTest.kt
> +    val testName = TestName()
Redundant ?

2023-01-04 20:22 UTC, FelixAlexK commented on app/src/androidTest/java/com/example/maraudersmap/SettingsActivityTest.kt
> +            .perform(closeSoftKeyboard())
.perform(typeText("12")) .perform(closeSoftKeyboard()), Can be abbreviated by writing:.perform(replaceText("12"))

2023-01-04 20:22 UTC, FelixAlexK commented
This branch has conflicts that must be resolved!!

2023-01-05 00:59 UTC, julianertle commented on app/src/androidTest/java/com/example/maraudersmap/SettingsActivityTest.kt
> +    val testName = TestName()
Not redundant, needed for if (testName.methodName != "aCreateNewUserSuccessTest"){}

2023-01-05 01:17 UTC, julianertle commented on app/src/androidTest/java/com/example/maraudersmap/SettingsActivityTest.kt
> +            .perform(closeSoftKeyboard())
Very nice tip! Will change that

2023-01-05 01:20 UTC, julianertle commented on app/src/androidTest/java/com/example/maraudersmap/SettingsActivityTest.kt
> +class SettingsActivityTest {
Changed it

2023-01-05 01:32 UTC, julianertle commented
@FelixAlexK I requested a new review please check it out

2023-01-06 09:37 UTC, FelixAlexK approved these changes
Looks good

2023-01-06 09:37 UTC, merged